import Navbar from '@/components/ui/Navbar';
import { cn } from '@/libs/utils';
import ReactQueryProvider from '@/providers/ReactQueryProvider';
import '@/public/styles/globals.css';
import { Inter } from 'next/font/google';
/* import '@/app/rxjs'; */
const inter = Inter({ subsets: ['latin'] });
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          'h-screen w-screen flex  flex-col dark:bg-black bg-white gap-5 dark:text-white',
        )}
      >
        <ReactQueryProvider>
          <Navbar />
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
